// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 🔥 ここを実際のFirebaseプロジェクトの値に置き換えてください
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCDEFGHIJKLMNOPQRSTUVWXYZ1234567',  // 実際のWeb APIキー
    appId: '1:123456789012:web:abc123def456789012345',    // 実際のWeb App ID
    messagingSenderId: '123456789012',                     // 実際のSender ID
    projectId: 'gala-nomi-app-12345',                     // 実際のProject ID
    authDomain: 'gala-nomi-app-12345.firebaseapp.com',   // 実際のAuth Domain
    storageBucket: 'gala-nomi-app-12345.appspot.com',    // 実際のStorage Bucket
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABCDEFGHIJKLMNOPQRSTUVWXYZ1234567',
    appId: '1:123456789012:android:abc123def456789012345',
    messagingSenderId: '123456789012',
    projectId: 'gala-nomi-app-12345',
    storageBucket: 'gala-nomi-app-12345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABCDEFGHIJKLMNOPQRSTUVWXYZ1234567',
    appId: '1:123456789012:ios:abc123def456789012345',
    messagingSenderId: '123456789012',
    projectId: 'gala-nomi-app-12345',
    storageBucket: 'gala-nomi-app-12345.appspot.com',
    iosBundleId: 'com.example.galaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABCDEFGHIJKLMNOPQRSTUVWXYZ1234567',
    appId: '1:123456789012:ios:abc123def456789012345',
    messagingSenderId: '123456789012',
    projectId: 'gala-nomi-app-12345',
    storageBucket: 'gala-nomi-app-12345.appspot.com',
    iosBundleId: 'com.example.galaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABCDEFGHIJKLMNOPQRSTUVWXYZ1234567',
    appId: '1:123456789012:web:abc123def456789012345',
    messagingSenderId: '123456789012',
    projectId: 'gala-nomi-app-12345',
    authDomain: 'gala-nomi-app-12345.firebaseapp.com',
    storageBucket: 'gala-nomi-app-12345.appspot.com',
  );
}